name: Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: Test scalafix rules
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:17
          apps: scala-cli:1.2.0

      - name: Test rules
        run: sbt "test"
      - name: Test outputs 
        run: |
          tests=src/main/scala/test
          for file in Example1.scala Example2.scala ; do
            scala-cli run input/build.scala input/$tests/$file > input.out
            scala-cli run output/build.scala output/$tests/$file > output.out
            diff input.out output.out && echo "Test $file - ok" || exit 1
          done

      - name: Test circe-generic-extern tests 
        run: |
          scala-cli test input
          scala-cli test output
