name: Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: Test scalafix rules
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:17
          apps: scala-cli:1.2.0

      - name: Test rules
        run: sbt "test"
      - name: Test runtime 
        run: |
          diff <(scala-cli run input/build.scala input/src/main/scala/test/Example1.scala) <(scala-cli run output/build.scala output/src/main/scala/test/Example1.scala)
          diff <(scala-cli run input/build.scala input/src/main/scala/test/Example2.scala) <(scala-cli run output/build.scala output/src/main/scala/test/Example2.scala)